### ISSUE TITLE
Error handling on request could be better

### ISSUE THREAD

**Issue by LukeXF** [PaymentRails/javascript-sdk#11]
The error I get when making a request to one of your endpoints is:
```
{
  error: Malformed [Error]: Value is invalid
      at Request._callback (/Applications/Projects/smb-api/node_modules/paymentrails/dist/Client.js:36:36)
      at Request.self.callback (/Applications/Projects/smb-api/node_modules/request/request.js:185:22)
      at Request.emit (events.js:210:5)
      at Request.EventEmitter.emit (domain.js:499:23)
      at Request.<anonymous> (/Applications/Projects/smb-api/node_modules/request/request.js:1161:10)
      at Request.emit (events.js:210:5)
      at Request.EventEmitter.emit (domain.js:499:23)
      at IncomingMessage.<anonymous> (/Applications/Projects/smb-api/node_modules/request/request.js:1083:12)
      at Object.onceWrapper (events.js:299:28)
      at IncomingMessage.emit (events.js:215:7)
      at IncomingMessage.EventEmitter.emit (domain.js:499:23)
      at endReadableNT (_stream_readable.js:1183:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
}
```

Which doesn't actually help me debug my issue.

I went searching in `/node_modules/paymentrails/dist/Client.js` and I found after you load ` const data = JSON.parse(responseBody);` on line 28, then there's an errors' object inside of `data`.

Running `console.log(data.errors);` on the next line will load a helpful error:

```
[
  {
    code: 'invalid_field',
    message: 'Value is invalid',
    field: 'country'
  }
]
```

Am I doing something wrong where I'm not getting the correct errors thrown?

**Comment by LukeXF** [comment]
Ah I see your switch statement is returning:

```
 case 400:
    reject(new exceptions_1.Exceptions.Malformed(firstErr.message || "Not Found"));
    return;
```

Is it possible you can pass `field` through to the error as well?

Perhaps:
```
 case 400:
    reject(new exceptions_1.Exceptions.Malformed(`${firstErr.message}: ${firstErr.field}` || "Not Found"));
    return;
```

Which will return `error: Malformed [Error]: Value is invalid: country` for me - much more helpful!

**Comment by LukeXF** [comment]
Expanded the pull request to account for other 400 errors that don't contain a validation error.

For example:
- A duplicate email 400 error should only return `firstErr.message`
- Whereas a validation error (`invalid_field`) should contain `firstErr.message` and `firstErr.field`

```
case 400:
	const message = firstErr.code === 'invalid_field' ? `${firstErr.message}: ${firstErr.field}` : firstErr.message;
	reject(new exceptions_1.Exceptions.Malformed(message || 'Not Found'));
	return;
```

**Comment by LukeXF** [comment]
Closing this issue as my pull request has been merged 👍
