### ISSUE TITLE
Error: Payment is missing quote

### ISSUE THREAD

**Issue by Petro000** [PaymentRails/javascript-sdk#37]
**After running this code:**
```
const client = paymentrails.connect({
  key: KEY,
  secret: SECRET,
  environment: 'sandbox',
});

async function payToRecipient(recipientId) {
  const batch = await client.batch.create({
    description: "My Batch",
    sourceCurrency: "USD",
  });

  await client.payment.create(batch.id, {
    recipient: {
      id: recipientId
    },
    sourceAmount: '10.99',
  });

  return await client.batch.startProcessing(batch.id)
}

async function run() {
  console.log(
      await payToRecipient('R-VbpKBJR8z9mb3Gx518XvEX')
  )
}
```

**got error:**
```
(node:10644) UnhandledPromiseRejectionWarning: Error: Payment is missing quote
    at Request._callback (C:\Users\newsi\work\22_12\Aurign\test\node_modules\paymentrails\dist\Client.js:37:36)
    at Request.self.callback (C:\Users\newsi\work\22_12\Aurign\test\node_modules\request\request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (C:\Users\newsi\work\22_12\Aurign\test\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (C:\Users\newsi\work\22_12\Aurign\test\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by Sheikh-Aman** [comment]
This is not an error in SDK, but an error returned by the API.
This error denotes that a quote for this payment can't be generated.
